manifest:
  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: rosterloh
      url-base: git@github.com:rosterloh/nrf-projects.git

  projects:
    - name: zephyr
      revision: master
      west-commands: scripts/west-commands.yml
      import:
        name-whitelist:
          - cmsis
          - hal_nordic
          - lvgl
          - mbedtls
          - mcuboot
          - mcumgr
          - segger
          - tinycbor
          - tinycrypt
          - littlefs
          - nrf_hw_models

    - name: nrfxlib
      repo-path: sdk-nrfxlib
      revision: fa0bd769387f7627d41c6592ae4c2f449847b822
      path: nrfxlib
      remote: ncs

  self:
    path: nrf
