manifest:
  defaults:
    remote: zephyrproject
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: ncs
      url-base: https://github.com/NordicPlayground
    - name: rosterloh
      url-base: git@github.com:rosterloh/nrf-projects.git

  projects:
    - name: zephyr
      revision: 42c5b0a7fafa3360b8d835d4b76d7b1bebbe9237
      west-commands: scripts/west-commands.yml
    - name: ci-tools
      revision: c083680dd5e281218ddb47d0ceac5c5fd5619749
      path: tools/ci-tools
    - name: hal_nordic
      revision: 64f3473398f9fba11059dd0c7ae969e74f74f356
      path: modules/hal/nordic
    - name: mcumgr
      revision: 84934959d2d1722a23b7e7e200191ae4a6f96168
      path: modules/lib/mcumgr
    - name: nffs
      revision: bc62a2fa9d98ddb5d633c932ea199bc68e10f194
      path: modules/fs/nffs
    - name: openthread
      revision: 882e7074b5986027b85cb4f3ba1dc563a11ca013
      path: modules/lib/openthread
    - name: segger
      revision: 6fcf61606d6012d2c44129edc033f59331e268bc
      path: modules/debug/segger

    - name: nrfxlib
      revision: dc9e1fbd146f5032fd3651b1e7705d8b3258ecc2
      path: nrfxlib
      remote: ncs
      
    - name: mcuboot
      revision: 4d0c5fa488b27dbbd3e3223574d594d7648e0a17


  self:
    path: nrf
