manifest:
  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: ncs
      url-base: https://github.com/NordicPlayground
    - name: rosterloh
      url-base: git@github.com:rosterloh/nrf-projects.git

  projects:
    - name: zephyr
      revision: master
      west-commands: scripts/west-commands.yml
      import:
        name-whitelist:
          - cmsis
          - ci-tools
          - hal_nordic
          - hal_st
          - hal_stm32
          - lvgl
          - mcuboot
          - mcumgr
          - nffs
          - openthread
          - segger
          - littlefs

    - name: nrfxlib
      revision: 037cb2339ef13e71f0600fcc111700efaf799d08
      path: nrfxlib
      remote: ncs
      
  self:
    path: nrf
