manifest:
  defaults:
    remote: zephyrproject
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: rosterloh
      url-base: git@github.com:rosterloh/nrf-projects.git

  projects:
    - name: zephyr
      revision: f4296a03caa7c9172bb60862a7a5bbb209713470
      west-commands: scripts/west-commands.yml
    - name: ci-tools
      revision: 20aa511fbd302ba8429a9ab04ee96c201b547743
      path: tools/ci-tools
    - name: hal_nordic
      revision: e0bfd6f253ca6a5e87b6f53a8bb317bd6f483511
      path: modules/hal/nordic
    - name: mcumgr
      revision: 84934959d2d1722a23b7e7e200191ae4a6f96168
      path: modules/lib/mcumgr
    - name: nffs
      revision: bc62a2fa9d98ddb5d633c932ea199bc68e10f194
      path: modules/fs/nffs
    - name: openthread
      revision: 882e7074b5986027b85cb4f3ba1dc563a11ca013
      path: modules/lib/openthread
    - name: segger
      revision: 6fcf61606d6012d2c44129edc033f59331e268bc
      path: modules/debug/segger

    - name: mcuboot
      revision: 4d0c5fa488b27dbbd3e3223574d594d7648e0a17

  self:
    path: nrf
