manifest:
  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: rosterloh
      url-base: git@github.com:rosterloh/nrf-projects.git

  projects:
    - name: zephyr
      revision: master
      west-commands: scripts/west-commands.yml
      import:
        name-whitelist:
          - cmsis
          - ci-tools
          - esp-idf
          - hal_nordic
          - hal_st
          - hal_stm32
          - libmetal
          - lvgl
          - mbedtls
          - mcuboot
          - mcumgr
          - net-tools
          - open-amp
          - segger
          - tinycbor
          - tinycrypt
          - littlefs
          - nrf_hw_models
          - hal_xtensa

    - name: nrfxlib
      repo-path: sdk-nrfxlib
      revision: 3eed8cbd8f6b0fa38aaa6b7d5d0e33bd7408f0d1
      path: nrfxlib
      remote: ncs

  self:
    path: nrf
